ExeGuide/ExeGuide/Areas/Editor/Controllers/ExerciseController.cs
using ExeGuide.Areas.Editor.Controllers;
using ExeGuide.Core.Models.Exercises;
using ExeGuide.Core.Services.Exercises;
using ExeGuide.Core.Services.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ExeGuide.Areas.Editor.Models;
using ExeGuide.DataBase.Infrastructure;
using static ExeGuide.DataBase.Data.Constants.EditorConstants;
using ExeGuide.Core.Services.Exercises.Models;
using System.Reflection.Metadata;
using ExeGuide.DataBase.Data;
using ExeGuide.DataBase.Data.Entities;

namespace ExeGuide.Areas.Editor.Controllers
{
    public class ExerciseController : EditorController
    {
        private readonly ExeGuideDbContext context;
        private readonly IExerciseService exerciseService;
        private readonly IUserService users;
        public ExerciseController(IExerciseService exerciseService, IUserService userService, ExeGuideDbContext _context)
        {
            this.exerciseService = exerciseService;
            this.users = userService;
            context = _context;
        }


        /// <summary>
        /// This method returns a view with all exercises in the databse
        /// </summary>
        /// <param name="query"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllExercisesQueryModel query)
        {
            bool userExist = context.TrainingUsers.Any(t => t.Id == User.Id());
            if (!userExist)
            {
                var newUser = new TrainingUser()
                {
                    Id = User.Id()
                };
                context.TrainingUsers.Add(newUser);
                context.SaveChanges();
            }
            var queryResults = this.exerciseService.All(
                query.SearchTerm,
                query.MainCategoryName,
                query.SubCategoryName,
                query.EquipmentName,
                query.CurrentPage,
                AllExercisesQueryModel.ExercisesPerPage);

            query.TotalExerciseCount = queryResults.TotalExercisesCount;

            query.Exercises = queryResults.Exercises;

            var mainCategoryName = exerciseService.AllMainCategoriesNames();
            var subCategoryName = exerciseService.AllSubCategoriesNames();
            var equipmentName = exerciseService.AllEquipmentNames();
            query.MainCategory = mainCategoryName;
            query.SubCategory = subCategoryName;
            query.Equipment = equipmentName;

            return View(query);
        }


        /// <summary>
        /// This method returns a view containing more information about the chosen exercise
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Details(int id)
        {
            if (!this.exerciseService.Exists(id))
            {
                return BadRequest();
            }
            var exerciseModel = exerciseService.ExerciseDetailsById(id);
            return View(exerciseModel);
        }


        /// <summary>
        /// This method returns a view where the editor can add a new exercise to the database
        /// </summary>
        /// <returns></returns>
        [Authorize]
        [HttpGet]
        public IActionResult Add()
        {

            return View(new ExerciseFormModel
            {
                MainCategories = exerciseService.AllMainCategories(),
                SubCategories = exerciseService.AllSubCategories(),
                Equipments = exerciseService.AllEquipments()
            });
        }


        /// <summary>
        /// Unpon inserting the new infomation and saving it this method saves the new exercise to the databse
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(ExerciseFormModel model)
        {

            if (!this.exerciseService.MainCategoryExists(model.MainCategoryId))
            {
                this.ModelState.AddModelError(nameof(model.MainCategoryId), "Main category does not exist");
            }
            if (!this.exerciseService.SubCategoryExists(model.SubCategoryId))
            {
                this.ModelState.AddModelError(nameof(model.SubCategoryId), "Subcategory does not exist");
            }
            if (!this.exerciseService.EquipmentExists(model.EquipmentId))
            {
                this.ModelState.AddModelError(nameof(model.EquipmentId), "Equipment does not exist");
            }
            if (!ModelState.IsValid)
            {
                model.MainCategories = this.exerciseService.AllMainCategories();
                model.SubCategories = this.exerciseService.AllSubCategories();
                model.Equipments = this.exerciseService.AllEquipments();

                return View(model);
            }

            

            var newExercise = this.exerciseService.Create(model.Name, model.Description, model.ImageUrl, model.MainCategoryId, model.SubCategoryId, model.EquipmentId);

            return RedirectToAction(nameof(Details), new { id = newExercise });
        }


        /// <summary>
        /// This method returns a view where the editor can see what exercise he is about to delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (!exerciseService.Exists(id))
            {
                return BadRequest();
            }

            var exercise = exerciseService.ExerciseDetailsById(id);

            var model = new ExerciseDetailsServiceModel
            {
                Name = exercise.Name,
                ImageUrl = exercise.ImageUrl
            };

            return View(model);
        }



        /// <summary>
        /// When the editor is shure about his choise, upon clicking the delete button this method activates and deletes the exercise from the database
        /// </summary>
        /// <param name="exercise"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(ExerciseDetailsServiceModel exercise)
        {
            if (!exerciseService.Exists(exercise.Id))
            {
                return BadRequest();
            }
            exerciseService.Delete(exercise.Id);
            return RedirectToAction("Index", "Editor");
        }

        
        /// <summary>
        /// This method opens a view where the editor will be able to edit the exercise he choses
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!exerciseService.Exists(id))
            {
                return BadRequest();

            }

            var exercise = exerciseService.ExerciseDetailsById(id);

            var mainCategory = exerciseService.MainCategoryId(exercise.Id);
            var subCategory = exerciseService.SubCategoryId(exercise.Id);
            var equipment = exerciseService.EquipmentId(exercise.Id);

            var houseModel = new ExerciseFormModel()
            {
                Name = exercise.Name,
                Description = exercise.Description,
                ImageUrl = exercise.ImageUrl,
                MainCategoryId = mainCategory,
                MainCategories = exerciseService.AllMainCategories(),
                SubCategoryId = subCategory,
                SubCategories = exerciseService.AllSubCategories(),
                EquipmentId = equipment,
                Equipments = exerciseService.AllEquipments()
            };
            return View(houseModel);
        }


        /// <summary>
        /// Uppon chosing and editing the exercise this method activates and saves the changes in the database
        /// </summary>
        /// <param name="id"></param>
        /// <param name="exercise"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, ExerciseFormModel exercise)
        {
            if (!exerciseService.Exists(id))
            {
                return View();

            }
            if (!exerciseService.MainCategoryExists(exercise.MainCategoryId))
            {
                ModelState.AddModelError(nameof(exercise.MainCategoryId), "Main category does not exist!");
            }
            if (!exerciseService.SubCategoryExists(exercise.SubCategoryId))
            {
                ModelState.AddModelError(nameof(exercise.SubCategoryId), "Subcategory does not exist!");
            }
            if (!exerciseService.EquipmentExists(exercise.EquipmentId))
            {
                ModelState.AddModelError(nameof(exercise.EquipmentId), "Equipment does not exist!");
            }

            if (!ModelState.IsValid)
            {
                exercise.MainCategories = exerciseService.AllMainCategories();
                exercise.SubCategories = exerciseService.AllSubCategories();
                exercise.Equipments = exerciseService.AllEquipments();

                return View(exercise);
            }
            exerciseService.Edit(id, exercise.Name, exercise.Description, exercise.ImageUrl, exercise.MainCategoryId, exercise.SubCategoryId, exercise.EquipmentId);

            return RedirectToAction(nameof(Details), new { id = id });
        }


    }
}

ExeGuide/ExeGuide/Areas/Writer/Controllers/ArticleController.cs
using ExeGuide.Areas.Writer.Models;
using ExeGuide.Core.Services.Articles;
using ExeGuide.Core.Services.Articles.Models;
using ExeGuide.DataBase.Data;
using ExeGuide.DataBase.Data.Entities;
using ExeGuide.DataBase.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExeGuide.Areas.Writer.Controllers
{
    public class ArticleController : WriterController
    {
        private readonly ExeGuideDbContext context;
        private readonly IArticleService articleService;
        public ArticleController(IArticleService _articleService,ExeGuideDbContext _context)
        {
            articleService = _articleService;
            context = _context;
        }


        /// <summary>
        /// This method is for adding a new article
        /// </summary>
        /// <returns>Returns a view where the writer can add a new article </returns>
        [Authorize]
        [HttpGet]
        public IActionResult Add()
        {
            bool userExist = context.TrainingUsers.Any(t => t.Id == User.Id());
            if (!userExist)
            {
                var newUser = new TrainingUser()
                {
                    Id = User.Id()
                };
                context.TrainingUsers.Add(newUser);
                context.SaveChanges();
            }

            return View(new ArticleFormModel
            {
                ArticleCategory = articleService.AllCategories()

            });
        }


        /// <summary>
        /// This post method adds the newly created article to the database
        /// </summary>
        /// <param name="model">The newly created article</param>
        /// <returns>Adds the article to the databse</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(ArticleFormModel model)
        {

            if (!this.articleService.CategoryExists(model.CategoryId))
            {
                this.ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist");
            }

            if (!ModelState.IsValid)
            {

                model.ArticleCategory = this.articleService.AllCategories();

                return View(model);
            }
            this.articleService.Create(model.Title, model.ArticleText, model.ImageUrl, model.CategoryId);

            return RedirectToAction("Index","Writer");
        }

        /// <summary>
        /// The method returns a view where the writeer to see if this is the article that he actually wants to delete
        /// </summary>
        /// <param name="id">Article id</param>
        /// <returns>Returns a view</returns>
        [Authorize]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (!articleService.Exists(id))
            {
                return BadRequest();
            }

            var article = articleService.ArticleById(id);

            var model = new ArticleServiceModel
            {
                Title = article.Title,
                ImageUrl = article.ImageUrl
            };

            return View(model);
        }

        /// <summary>
        /// The method deletes the chosen article by the writer
        /// </summary>
        /// <param name="article">The chosen article</param>
        /// <returns>Deletes the article from the database</returns>
        [HttpPost]
        public IActionResult Delete(ArticleServiceModel article)
        {
            if (!articleService.Exists(article.Id))
            {
                return BadRequest();
            }
            articleService.Delete(article.Id);
            return RedirectToAction("Index", "Writer");
        }


        /// <summary>
        /// With this class the writer will open a view where he can edit the things he want
        /// </summary>
        /// <param name="id">The article Id</param>
        /// <returns>Edit view</returns>
        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!articleService.Exists(id))
            {
                return BadRequest();

            }

            var article = articleService.ArticleById(id);

           
            var category = articleService.CategoryId(article.Id);

            var articleModel = new ArticleFormModel()
            {
                Title = article.Title,
                ImageUrl = article.ImageUrl,
                ArticleText = article.ArticleText,
                ArticleCategory = articleService.AllCategories()
                
            };
            return View(articleModel);
        }




        /// <summary>
        /// This method inserts the changes in the article in the database
        /// </summary>
        /// <param name="id"> The article's Id</param>
        /// <param name="article">The chosen article</param>
        /// <returns>Changes the edited information</returns>
        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, ArticleFormModel article)
        {
            if (!articleService.Exists(id))
            {
                return View();

            }
            if (!this.articleService.CategoryExists(article.CategoryId))
            {
                this.ModelState.AddModelError(nameof(article.CategoryId), "Category does not exist");
            }

            if (!ModelState.IsValid)
            {

                article.ArticleCategory = articleService.AllCategories();

                return View(article);
            }
            articleService.Edit(id, article.Title, article.ArticleText, article.ImageUrl, article.CategoryId);

            return RedirectToAction("Index","Writer");
        }

    }
}

ExeGuide/ExeGuide/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" style="background-color: #eab85d;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainingHelper</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrainingHelper.styles.css" asp-append-version="true" />
</head>
<body style="background-color:transparent;
    margin-bottom: 50px;
    background-repeat: no-repeat;
    width: auto;
    height: 600px;
    background-size: cover;">
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-image: linear-gradient(to right,#64646c,rgb(200,200,220));">
            <div class="container-fluid" style="background-color: transparent; border:none;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white">ExeGuide</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <div class="vertLine"> </div>
                        <li class="nav-item" >
                            <a class="nav-link text-white" asp-area="" asp-controller="Exercise" asp-action="All">All Exercises</a>
                        </li>
                        <li class="nav-item" >
                            <a class="nav-link text-white" asp-area="" asp-controller="Article" asp-action="All" >Articles</a>
                        </li>

                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <div class="vertLine"> </div>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Exercise" asp-action="Mine">My Favourites</a>
                            </li>
                        }
                        @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated && this.User.IsInRole("Editing"))
                        {
                            <div class="vertLine"> </div>
                            <li class="nav-item" >
                                <a class="nav-link text-white" asp-area="" asp-controller="Exercise" asp-action="Add">Add Exercises</a>
                            </li>
                        }
                        @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated && this.User.IsInRole("Writer"))
                        {
                            <div class="vertLine"> </div>
                            <li class="nav-item" >
                                <a class="nav-link text-white" asp-area="" asp-controller="Article" asp-action="Add" >Add Article</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position: fixed;bottom: 0; width: 100%;height: 30px; border:none; background-color:#64646c" st>
        <div class="container" style="color:#64646c">
            2022 - TrainingHelper
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>